Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2021-11, with the labels that each got.

#192 Return OpenTelemetryConfiguration.Builder when adding resource attributes
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
  sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
Labels: type: bug, version: bump minor

#194 Add tests for agent+manual instrumentation
  .circleci/config.yml
  Makefile
  Tiltfile
  examples/spring-agent-manual/build.gradle
  examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/Application.java
  examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/HelloController.java
  examples/spring-agent-manual/src/main/resources/application.properties
  settings.gradle
  smoke-tests/smoke-tests-agent-manual/app.dockerfile
  smoke-tests/smoke-tests-agent-manual/bats.dockerfile
  smoke-tests/smoke-tests-agent-manual/collector.dockerfile
  smoke-tests/smoke-tests-agent-manual/data.json
  smoke-tests/smoke-tests-agent-manual/docker-compose.yml
  smoke-tests/smoke-tests-agent-manual/otel-collector-config.yaml
  smoke-tests/smoke-tests-agent-manual/smoke.bats
  smoke-tests/smoke-tests-agent-only/app.dockerfile
  smoke-tests/smoke-tests-agent-only/bats.dockerfile
  smoke-tests/smoke-tests-agent-only/collector.dockerfile
  smoke-tests/smoke-tests-agent-only/data.json
  smoke-tests/smoke-tests-agent-only/docker-compose.yml
  smoke-tests/smoke-tests-agent-only/otel-collector-config.yaml
  smoke-tests/smoke-tests-agent-only/smoke.bats
Labels: type: maintenance, version: no bump

#199 teach gradle/make to display the project version
  Makefile
  build.gradle
Labels: type: maintenance, version: no bump

#200 Update OpenTelemetry SDK and Agent
  README.md
  agent/build.gradle
  build.gradle
Labels: version: bump minor, type: maintenance

#197 Test SDK-only traces (& smoke duplication reduction)
  .circleci/config.yml
  .gitignore
  Makefile
  build.gradle
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
  smoke-tests/apps/.gitkeep
  smoke-tests/collector/otel-collector-config.yaml
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-agent-manual.bats
  smoke-tests/smoke-agent-only.bats
  smoke-tests/smoke-sdk.bats
  smoke-tests/smoke-tests-agent-manual/app.dockerfile
  smoke-tests/smoke-tests-agent-manual/bats.dockerfile
  smoke-tests/smoke-tests-agent-manual/collector.dockerfile
  smoke-tests/smoke-tests-agent-manual/docker-compose.yml
  smoke-tests/smoke-tests-agent-manual/smoke.bats
  smoke-tests/smoke-tests-agent-only/app.dockerfile
  smoke-tests/smoke-tests-agent-only/bats.dockerfile
  smoke-tests/smoke-tests-agent-only/collector.dockerfile
  smoke-tests/smoke-tests-agent-only/data.json
  smoke-tests/smoke-tests-agent-only/docker-compose.yml
  smoke-tests/smoke-tests-agent-only/otel-collector-config.yaml
  smoke-tests/smoke-tests-agent-only/smoke.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance, version: no bump

#202 Add support for properties files
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
Labels: type: enhancement, version: bump minor

#203 Add smoke test for baggage span processor
  examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/HelloController.java
  smoke-tests/smoke-agent-manual.bats
Labels: type: maintenance, version: no bump

#206 Add Smoke test for JVM metric being emitted
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-agent-only.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance, version: no bump

#205 Backfill unit tests
  build.gradle
  common/build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  common/src/test/java/io/honeycomb/opentelemetry/DistroMetadataTest.java
  common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
  custom/build.gradle
  custom/src/test/java/io/honeycomb/opentelemetry/DistroMetadataResourceProviderTest.java
  custom/src/test/java/io/honeycomb/opentelemetry/ServiceNameResourceProviderTest.java
  sdk/build.gradle
  sdk/src/test/java/io/honeycomb/opentelemetry/BaggageSpanProcessorTest.java
  sdk/src/test/java/io/honeycomb/opentelemetry/DeterministicTraceSamplerTest.java
  sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
Labels: version: bump minor, type: maintenance

#209 Update DeterminisitcSampler to use OTel core Parent/TraceIDRatio samplers
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
  sdk/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
  sdk/src/test/java/io/honeycomb/opentelemetry/DeterministicTraceSamplerTest.java
Labels: type: enhancement, version: bump minor

#210 Update SDK tests to validate returned OpenTelemtry instance
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
  sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
Labels: version: bump minor, type: maintenance

#214 Remove -all suffix from artifacts
  Makefile
  agent/build.gradle
  custom/build.gradle
  examples/spring-agent-manual/build.gradle
  examples/spring-agent-only/build.gradle
Labels: version: bump minor, type: maintenance

#215 Update dependabot to monthly
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will
