Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2021-05, with the labels that each got.

#48 Add SDK builder method for passing in BaggageSpanProcessor or any custom SpanProcessor
  README.md
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
  sdk/src/test/java/io/honeycomb/opentelemetry/HoneycombSdkTest.java
Labels: status: review needed

#45 Add maven publish
  .circleci/config.yml
  RELEASING.md
  agent/build.gradle
  build.gradle
  common/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/build.gradle
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: type: maintenance, version: no bump

#53 Create methods for adding arbitrary resource attributes
  docs/README.md
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: type: enhancement, version: bump minor

#50 DRY up constants between modules
  DEVELOPMENT.md
  agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: type: maintenance, version: no bump

#52 Fix: use additional span processors in SDK builder
  .github/dependabot.yml
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: type: bug, version: bump patch

#60 Add baggage propagator to the SDK
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: version: bump minor

#61 Prepare for 0.2.0 release
  CHANGELOG.md
  DEVELOPMENT.md
  README.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  docs/README.md
Labels: type: maintenance

#63 Fix readme download link [skip ci]
  README.md
Labels: version: no bump

#65 Fix Sontaype pom validator
  RELEASING.md
  agent/build.gradle
  build.gradle
  common/build.gradle
  sdk/build.gradle
Labels: version: bump patch

#68 Small changes to README
  README.md
Labels: type: documentation, version: no bump
