Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2021-09, with the labels that each got.

#121 Link to public dosc for SDK setup
  README.md
Labels: type: documentation

#126 docs: add OTEL version to readme
  README.md
  RELEASING.md
Labels: type: documentation

#124 Adds example apps
  .gitignore
  examples/README.md
  examples/spring-agent/build.gradle
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/Application.java
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/HelloController.java
  examples/spring-agent/src/main/resources/application.properties
  examples/spring-sdk/build.gradle
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/HelloController.java
  examples/spring-sdk/src/main/resources/application.properties
  settings.gradle
Labels: type: documentation, version: no bump

#132 Replace HoneycombSdk with OpenTelemetryConfiguration.Builder
  .gitignore
  Makefile
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/Application.java
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/HelloController.java
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/HelloController.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
  sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
Labels: type: enhancement

#134 Update OpenTelemetry SDK to 1.5.0 and agent to 1.5.3
  build.gradle
Labels: type: enhancement

#135 Add support for enabling OTel metrics
  agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
  common/build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement, version: bump minor

#138 Mike/document debug agent
  README.md
  sdk/build.gradle
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement

#137 Set spring boot port and update examples formatting
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/Application.java
  examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/HelloController.java
  examples/spring-agent/src/main/resources/application.properties
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
  examples/spring-sdk/src/main/resources/application.properties
Labels: type: maintenance

#136 automate nexus publish/close/release
  .circleci/config.yml
  build.gradle
Labels: type: maintenance, version: no bump

#139 Ensure SDK configurator applies core SDK resource attributes
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: bug

#145 add javadoc for method param
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: maintenance

#146 Bump otel to 1.6.0
  build.gradle
  custom/src/main/java/io/honeycomb/opentelemetry/DistroMetadataResourceProvider.java
  custom/src/main/java/io/honeycomb/opentelemetry/HoneycombSdkTracerProviderConfigurer.java
  custom/src/main/java/io/honeycomb/opentelemetry/ServiceNameResourceProvider.java
Labels: type: maintenance

#149 fix: metrics export
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
Labels: type: bug, version: bump patch

#148 Use built-in OTel resources for OS & runtime
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  sdk/build.gradle
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: maintenance, version: bump patch

#155 docs: sonatype release is automated
  RELEASING.md
Labels: type: documentation
