Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2021-10, with the labels that each got.

#160 re-add java runtime version distro metadata
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: type: bug, version: bump minor

#162 fix: Remove google guava dep that suppressed gRPC
  common/build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
Labels: type: bug, version: bump patch

#171 [docs] Remove docs from repo to prevent dupes and misses
  README.md
  docs/README.md
Labels: type: documentation, version: no bump
