Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2021-08, with the labels that each got.

#89 Make API Key and Dataset optional
  README.md
  agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Labels: version: bump minor

#92 Disable metrics by default
  agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
Labels: version: bump patch

#95 Add OSS lifecycle badge
  OSSMETADATA
  README.md
Labels: version: no bump

#97 Prepare for v0.4.0
  CHANGELOG.md
  DEVELOPMENT.md
  README.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  docs/README.md
Labels: type: maintenance, version: no bump
