Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-02, with the labels that each got.

#255 feat: provide more feedback to users to help configure for use in E&S
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement, version: bump minor

#257 Prepare v0.9.0
  CHANGELOG.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: type: maintenance, version: no bump

#261 docs: add maven badge
  README.md
Labels: type: documentation, version: no bump
