Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-10, with the labels that each got.

#347 maint: add release file
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#349 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: type: maintenance, version: no bump, merge at will

#348 Update Otel SDK and JavaAgent to v1.19.0/v1.19.1
  build.gradle
  examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/HelloController.java
  sdk/build.gradle
  smoke-tests/smoke-agent-manual.bats
Labels: version: bump minor, type: maintenance

#351 maint: upgrade gradle to 7.5
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: type: maintenance, version: no bump
