Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-03, with the labels that each got.

#267 Prepare v0.10.0 release
  CHANGELOG.md
  README.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: version: bump minor, type: maintenance

#273 bump otel version from 1.11 to 1.12.0
  build.gradle
Labels: type: maintenance, version: no bump

#277 prepare 1.0.0 release
  CHANGELOG.md
  README.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: status: blocked
