Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-06, with the labels that each got.

#310 Fixed false warning when OTEL_SERVICE_NAME was present.
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
Labels: type: bug, version: bump patch

#300 Add OTLP version to headers (HTTP & gRPC)
  RELEASING.md
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement, version: bump minor

#307 maint: upgrade otel versions to 1.14.0
  build.gradle
  common/build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
  common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/spanprocessors/BaggageSpanProcessor.java
  common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
  common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSamplerTest.java
  common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/spanprocessors/BaggageSpanProcessorTest.java
  custom/build.gradle
  sdk/build.gradle
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-agent-only.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance, version: bump patch

#313 docs: include onboard docs in releasing, move to top
  RELEASING.md
Labels: type: maintenance, version: no bump, merge at will

#316 Decorate existing Sampler with DeterministicTraceSampler instead of replacing it
  common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
  common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSamplerTest.java
  custom/src/main/java/io/honeycomb/opentelemetry/HoneycombAutoConfigurationCustomizerProvider.java
Labels: type: enhancement, version: bump minor, status: oncall

#319 produce a JSON of release info on build
  .gitignore
  build.gradle
Labels: type: maintenance, version: no bump
