Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-07, with the labels that each got.

#320 Prepare v1.3.0 release
  CHANGELOG.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: version: bump minor, type: maintenance

#323 maint: add un-versioned copy of agent to Github assets
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#325 maint: fix workflow that opens issue for docs update upon release
  .github/workflows/release.yml
Labels: type: maintenance, version: no bump, merge at will

#326 maint: include generated release.yml in published artifacts
  .circleci/config.yml
Labels: type: maintenance, version: no bump
