Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2022-11, with the labels that each got.

#362 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#363 ci: fix slack notify channel
  .circleci/config.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#364 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
