Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2023-04, with the labels that each got.

#411 docs: fix ci status badge
  README.md
Labels: type: documentation, version: no bump, no-changelog

#419 maint: update licenses in prep for release
  licenses/licenses.md
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/byte-buddy-dep-1.14.4.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/byte-buddy-dep-1.14.4.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-core-2.14.2.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-core-2.14.2.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-jr-objects-2.14.2.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-jr-objects-2.14.2.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/okhttp-4.10.0.jar/okhttp3/internal/publicsuffix/NOTICE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/slf4j-api-2.0.7.jar/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/slf4j-simple-2.0.7.jar/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-2.23.2.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-reporter-2.16.3.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-sender-okhttp3-2.16.3.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/LICENSE.renamed
  licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.25.0.jar/inst/okhttp3/internal/publicsuffix/NOTICE
Labels: type: maintenance

#418 rel: prep v1.5.0
  CHANGELOG.md
  README.md
  RELEASING.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Labels: no-changelog
