Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2024-03, with the labels that each got.

#448 feat: add support for classic ingest keys
  .circleci/config.yml
  common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
  common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement, version: bump minor

#449 rel: prep release v1.6.0
  CHANGELOG.md
  build.gradle
  common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
  licenses/licenses.md
Labels: no-changelog

#450 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#451 feat: return an OpenTelemetrySdk from the builder
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
  examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/HelloController.java
  sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Labels: type: enhancement, version: bump minor
