Repository honeycombio/honeycomb-opentelemetry-java, pull requests merged in 2024-04, with the labels that each got.

#453 maint: bump otel to 1.35/1.33.1
  build.gradle
  sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
Labels: type: maintenance, version: bump patch

#456 maint: update licenses for upcoming release
  licenses/licenses.md
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/byte-buddy-dep-1.14.12.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/byte-buddy-dep-1.14.12.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-annotations-2.17.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-annotations-2.17.0.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-core-2.17.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-core-2.17.0.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-databind-2.17.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-databind-2.17.0.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-dataformat-yaml-2.17.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-dataformat-yaml-2.17.0.jar/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/okhttp-4.12.0.jar/okhttp3/internal/publicsuffix/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/slf4j-api-2.0.12.jar/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/slf4j-simple-2.0.12.jar/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-2.27.1.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-reporter-3.3.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-sender-okhttp3-3.3.0.jar/META-INF/LICENSE
  licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/LICENSE.renamed
  licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/LICENSE.txt
  licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/NOTICE
  licenses/opentelemetry-javaagent-1.33.1.jar/inst/okhttp3/internal/publicsuffix/NOTICE
Labels: type: maintenance

#459 maint: Update project status and add status link in README
  OSSMETADATA
  README.md
Labels: type: maintenance, version: no bump
